---
title: "数据挖掘模型方法论"
author: "zhutx"
date: "2016/2/8"
output:
  html_document:
    toc: true
    toc_depth: 2
---

> essentially, all models are wrong, but some are useful.  -- George E.P. Box

# 数据挖掘建模的过程

## 掌握领域知识
学习领域知识是建立相应模型的最重要的一点, 在商业上的表现就是要有业务知识, 有商业直觉. 掌握的领域知识贯穿在建模过程始终.

## 确定模型的目标和评判准则
根据领域知识给出模型需要达到的目标, 并且为这个目标建立一个可度量的评判标准.

如果你碰到的是一个开放式的问题, 不像一般的为解决某个特定问题而去建模, 那么你需要先生成假设(hypothesis generation), 也就是凭借该领域的知识提出假设, 尽可能多得将想得到的假设记下来, 然后在后面通过建模分析进行验证或者推翻假设. 为什么要先生成假设, 因为如果不这样做你可能就会陷入数据和变量的汪洋大海, 最终项目的时间也是无法掌控, 参见[这里](http://discuss.analyticsvidhya.com/t/why-and-when-is-hypothesis-generation-important/2109/2)

## 增加数据集
对于模型来说, 数据越多越好, 变量越丰富越好, 尽量扩大数据源, 增加变量, 但是考虑到时间成本, 这就变成一个持续的过程, 一开始可以在小数据集上就先开始后面的建模, 甚至在没有数据的情况下也要能给出一个尽可能合理的模型.

## 数据预处理
这一块包含传统的数据清洗, 数据缺失值和异常值的处理, 数据的统计描述等.

## 特征工程
参见[特征工程](./特征工程.html)

## 使用多种算法

## 算法调参

## 使用组合办法
ensemble method 是现在 kaggle 比赛上的热门通用办法, 就是将各种算法得到的结果进行组合得到一个性能更好, 更健壮的算法.

组合办法一般可以分为三个步骤(参考 Introduction To Ensemble Learning):

1. **生成组合(ensemble generation)** 这个步骤就是生成基础的模型作为组合使用的输入. 如果基础模型所使用的是同种算法那么这些模型称为是同类的, 也就是说这些同类的模型可能只是所使用的数据集不同, 这里面又可以继续分为是数据集的不同采样, 或者是使用的不同的变量作为输入. 一般认为使用异类的基础模型会更好些.
2. **组合修剪(ensemble pruning)** 这一步主要就是对之前得到的基础组合进行筛选, 以期得到更高的准确率(或者/和)更少的计算量. 筛选的办法可以用划分法或者搜索法, 划分法就是根据事先给定的准则来直接筛选, 搜索法判定是否要筛掉一个基础模型的依据是加上或者删掉这个基础模型对最终的组合模型的影响.
3. **组合集成(ensemble integration)** 组合集成可以分为糅合和选择两种办法, 糅合就是将筛选好的基础模型结果组合成一个最终的结果, 选择则是每次预测都在基础模型里挑出可能性能最好模型作预测.

## 交叉验证


